data_60s = [
    {
     "name": "Aage Bhi Jaane Na",
     "artist": ["Ravi", "Asha Bhosle"],
     "movie": "Waqt",
     "location_clip": "./Clips/Aage Bhi Jaane Na.mp3",
     "location_main": "./Main song/Aage Bhi Jaane Na.mp3"
     },
    {
      "name": "Bekarar Karke Hume",
      "artist": "Hemanta Kumar",
      "movie": "Bees Saal Baad",
      "location_clip": "./Clips/Bekarar Karke Hume.mp3",
      "location_main": "./Main song/Bekarar Karke Hume.mp3",
    },
    {
      "name": "Chup Gaye Saare Nazaare",
      "artist": ["Lata Mangeshkar", "Mohammed Rafi"],
      "movie": "Do Raaste",
      "location_clip": "./Clips/Chup Gaye Saare Nazaare.mp3",
      "location_main": "./Main song/Chup Gaye Saare Nazaare.mp3",
    },
    {
      "name": "Deewanon Se Ye Mat Poocho",
      "artist": "Mukesh",
      "movie": "Upkar",
      "location_clip": "./Clips/Deewanon Se Ye Mat Poocho.mp3",
      "location_main": "./Main song/Deewanon Se Ye Mat Poocho.mp3",
    },
    {
      "name": "Baghon Mein Bahar Hai",
      "artist": ["Lata Mangeshkar", "Mohammed Rafi"],
      "movie": "Aradhana",
      "location_clip": "./Clips/Baghon Mein Bahar Hai.mp3",
      "location_main": "./Main song/Baghon Mein Bahar Hai.mp3",
    },
    {
      "name": "Har Dil Jo Pyaar Karega",
      "artist": ["Lata Mangeshkar", " Mukesh", "Mahendra Kapoor"],
      "movie": "Sangam",
      "location_clip": "./Clips/Har Dil Jo Pyaar Karega.mp3",
      "location_main": "./Main song/Har Dil Jo Pyaar Karega.mp3",
    },
    {
      "name": "Chahoonga Main Tujhe",
      "artist": "Mohammed Rafi",
      "movie": "Dosti",
      "location_clip": "./Clips/Chahoonga Main Tujhe.mp3",
      "location_main": "./Main song/Chahoonga Main Tujhe.mp3",
    },
    {
      "name": "Isharon Isharon Men Dil Lenewale",
      "artist": "O.P.Nayyar",
      "movie": "Kashmir Ki Kali",
      "location_clip": "./Clips/Isharon Isharon Men Dil Lenewale.mp3",
      "location_main": "./Main song/Isharon Isharon Men Dil Lenewale.mp3",
    },
    {
      "name": "Jhumka Gira Re",
      "artist": "Asha Bhosle",
      "movie": "Mera Saaya",
      "location_clip": "./Clips/Jhumka Gira Re.mp3",
      "location_main": "./Main song/Jhumka Gira Re.mp3",
    },
    {
      "name": "Milti Hai Zindagi Mein Mohabbat",
      "artist": ["Ravi", "Lata Mangeshkar"],
      "movie": "Aakhen",
      "location_clip": "./Clips/Milti Hai Zindagi Mein Mohabbat.mp3",
      "location_main": "./Main song/Milti Hai Zindagi Mein Mohabbat.mp3",
    },
    {
      "name": "Likhe Jo Khat Tujhe",
      "artist": "Mohammed Rafi",
      "movie": "Kanyadaan",
      "location_clip": "./Clips/Likhe Jo Khat Tujhe.mp3",
      "location_main": "./Main song/Likhe Jo Khat Tujhe.mp3",
    },
    {
      "name": "Jo Wada Kiya Wo",
      "artist": ["Lata Mangeshkar", "Mohammed Rafi"],
      "movie": "Taj Mahal",
      "location_clip": "./Clips/Jo Wada Kiya Wo.mp3",
      "location_main": "./Main song/Jo Wada Kiya Wo.mp3",
    },
    {
      "name": "Roop Tera Mastana",
      "artist": "Kishore Kumar",
      "movie": "Aradhana",
      "location_clip": "./Clips/Roop Tera Mastana.mp3",
      "location_main": "./Main song/Roop Tera Mastana.mp3",
    },
    {
      "name": "Mere Sapno Ki Rani",
      "artist": "Kishore Kumar",
      "movie": "Aradhana",
      "location_clip": "./Clips/Mere Sapno Ki Rani.mp3",
      "location_main": "./Main song/Mere Sapno Ki Rani.mp3",
    },
    {
      "name": "O Mere Sona Re Sona Re",
      "artist": ["Asha Bhosle", "Mohammed Rafi"],
      "movie": "Teesri Manzil",
      "location_clip": "./Clips/O Mere Sona Re Sona Re.mp3",
      "location_main": "./Main song/O Mere Sona Re Sona Re.mp3",
    },
    {
      "name": "Tera Mera Pyaar Amar",
      "artist": ["Lata Mangeshkar", " Shankar-Jaikishan"],
      "movie": "Asli-Naqli",
      "location_clip": "./Clips/Tera Mera Pyaar Amar.mp3",
      "location_main": "./Main song/Tera Mera Pyaar Amar.mp3",
    },
    {
      "name": "Yeh Reshmi Zulfen",
      "artist": "Mohammed Rafi",
      "movie": "Do Raaste",
      "location_clip": "./Clips/Yeh Reshmi Zulfen.mp3",
      "location_main": "./Main song/Yeh Reshmi Zulfen.mp3",
    },
    {
      "name": "Hothon Mein Aisi Baat",
      "artist": "S.D.Burman",
      "movie": "Jewel Thief",
      "location_clip": "./Clips/Hothon Mein Aisi Baat.mp3",
      "location_main": "./Main song/Hothon Mein Aisi Baat.mp3",
    },
    {
      "name": "Tumse Achchha Kaun Ha",
      "artist": "Mohammed Rafi",
      "movie": "Janwar",
      "location_clip": "./Clips/Tumse Achchha Kaun Ha.mp3",
      "location_main": "./Main song/Tumse Achchha Kaun Ha.mp3",
    },
    {
      "name": "Tauba Yeh Matwali Chaal",
      "artist": "Mukesh",
      "movie": "Patthar Ke Sanam",
      "location_clip": "./Clips/Tauba Yeh Matwali Chaal.mp3",
      "location_main": "./Main song/Tauba Yeh Matwali Chaal.mp3",
    },
    {
      "name": "Chandan Sa Badan Chanchal Chit ",
      "artist": "Lata Mangeshkar",
      "movie": "Saraswatichandra",
      "location_clip": "./Clips/Chandan Sa Badan Chanchal Chit .mp3",
      "location_main": "./Main song/Chandan Sa Badan Chanchal Chit .mp3",
    },
]


data_2000 = [
    {
      "name": "Tum Se Hi",
      "artist": "Mohit Chauhan",
      "movie": "Jab We Met",
      "location_clip": "./Clips/2000/Tum Se Hi.mp3",
      "location_main": "./Main song/2000/Tum Se Hi.mp3",
    },
    {
      "name": "Zara Zara",
      "artist": "Bombay Jayashri",
      "movie": "Rehnaa Hai Terre Dil Mein",
      "location_clip": "./Clips/2000/Zara Zara.mp3",
      "location_main": "./Main song/2000/Zara Zara.mp3",
    },
    {
      "name": "Pehli Nazar Mein",
      "artist": "Atif Aslam",
      "movie": "Race",
      "location_clip": "./Clips/2000/Pehli Nazar Mein.mp3",
      "location_main": "./Main song/2000/Pehli Nazar Mein.mp3",
    },
   {
      "name": "Woh Lamhe Who Baatein",
      "movie": "Zeher",
      "artist": "Atif Aslam",
      "location_clip": "./Clips/2000/Woh Lamhe Who Baatein.mp3",
      "location_main": "./Main song/2000/Woh Lamhe Who Baatein.mp3",
    },
    {
      "name": "Ek Pal Ka Jeena",
      "artist": "Lucky Ali",
      "movie": "Kaho Na Pyaar Hai",
      "location_clip": "./Clips/2000/Ek Pal Ka Jeena.mp3",
      "location_main": "./Main song/2000/Ek Pal Ka Jeena.mp3",
    },
   {
      "name": "Koi Kahe Kehta Rahe",
      "artist": ["Shankar Mahadevan", "Shaan", "KK"],
      "movie": "Dil Chahta Hai",
      "location_clip": "./Clips/2000/Koi Kahe Kehta Rahe.mp3",
      "location_main": "./Main song/2000/Koi Kahe Kehta Rahe.mp3",
    },
    # {
    #   "name": "Tauba Yeh Matwali Chaal",
    #   "artist": "Mukesh",
    #   "movie": "Patthar Ke Sanam",
    #   "location_clip": "./Clips/Tauba Yeh Matwali Chaal.mp3",
    #   "location_main": "./Main song/Tauba Yeh Matwali Chaal.mp3",
    # },
    # {
    #   "name": "Tauba Yeh Matwali Chaal",
    #   "artist": "Mukesh",
    #   "movie": "Patthar Ke Sanam",
    #   "location_clip": "./Clips/Tauba Yeh Matwali Chaal.mp3",
    #   "location_main": "./Main song/Tauba Yeh Matwali Chaal.mp3",
    # },
]